-- Add new columns to tblsummary table for staff tracking
ALTER TABLE `tblsummary` 
ADD COLUMN `STAFF_ID` int(11) NULL AFTER `USERID`,
ADD COLUMN `STAFF_NAME` varchar(255) NULL AFTER `STAFF_ID`,
ADD COLUMN `CONFIRMATION_DATE` datetime NULL AFTER `STAFF_NAME`,
ADD COLUMN `CANCELLATION_DATE` datetime NULL AFTER `CONFIRMATION_DATE`;
